### ISSUE TITLE
I met a problem: fuel.config_parser.ConfigurationError: Configuration not set and no default provided: data_path. 

### ISSUE THREAD

**Issue by wangxiao5791509** [CuriousAI/ladder#12] opened 2016-07-02 08:24 UTC
wangxiao@GTX980:~/Desktop/ladder-master$ ./run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec gauss --denoising-cost-x 2000,0,0,0,0,0,0 --labeled-samples 60000 --unlabeled-samples 60000 --seed 1 -- mnist_all_bottom
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
ERROR:main:Subprocess returned fatal: Not a git repository (or any of the parent directories): .git
INFO:main:Logging into results/mnist_all_bottom0/log.txt
INFO:main:== COMMAND LINE ==
INFO:main:./run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec gauss --denoising-cost-x 2000,0,0,0,0,0,0 --labeled-samples 60000 --unlabeled-samples 60000 --seed 1 -- mnist_all_bottom
INFO:main:== PARAMETERS ==
INFO:main: zestbn              : bugfix               
INFO:main: dseed               : 1                    
INFO:main: top_c               : 1                    
INFO:main: super_noise_std     : 0.3                  
INFO:main: batch_size          : 100                  
INFO:main: dataset             : mnist                
INFO:main: valid_set_size      : 10000                
INFO:main: num_epochs          : 150                  
INFO:main: whiten_zca          : 0                    
INFO:main: unlabeled_samples   : 60000                
INFO:main: decoder_spec        : ('gauss',)           
INFO:main: valid_batch_size    : 100                  
INFO:main: denoising_cost_x    : (2000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0) 
INFO:main: f_local_noise_std   : 0.3                  
INFO:main: cmd                 : train                
INFO:main: act                 : relu                 
INFO:main: lrate_decay         : 0.67                 
INFO:main: seed                : 1                    
INFO:main: lr                  : 0.002                
INFO:main: save_to             : mnist_all_bottom     
INFO:main: save_dir            : results/mnist_all_bottom0 
INFO:main: commit              :                      
INFO:main: contrast_norm       : 0                    
INFO:main: encoder_layers      : ('1000', '500', '250', '250', '250', '10') 
INFO:main: labeled_samples     : 60000                
Traceback (most recent call last):
  File "./run.py", line 651, in <module>
    if train(d) is None:
  File "./run.py", line 405, in train
    in_dim, data, whiten, cnorm = setup_data(p, test_set=False)
  File "./run.py", line 240, in setup_data
    train_set = dataset_class("train")
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 36, in __init__
    super(MNIST, self).__init__(self.data_path, which_set, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 40, in data_path
    return os.path.join(config.data_path, self.filename)
  File "/usr/local/lib/python2.7/dist-packages/fuel/config_parser.py", line 101, in __getattr__
    "provided: {}.".format(key))
fuel.config_parser.ConfigurationError: Configuration not set and no default provided: data_path.
wangxiao@GTX980:~/Desktop/ladder-master$ ./run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec 0-0-0-0-0-0-gauss --denoising-cost-x 0,0,0,0,0,0,2 --labeled-samples 60000 --unlabeled-samples 60000 --seed 1 -- mnist_all_gamma
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
ERROR:main:Subprocess returned fatal: Not a git repository (or any of the parent directories): .git
INFO:main:Logging into results/mnist_all_gamma0/log.txt
INFO:main:== COMMAND LINE ==
INFO:main:./run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec 0-0-0-0-0-0-gauss --denoising-cost-x 0,0,0,0,0,0,2 --labeled-samples 60000 --unlabeled-samples 60000 --seed 1 -- mnist_all_gamma
INFO:main:== PARAMETERS ==
INFO:main: zestbn              : bugfix               
INFO:main: dseed               : 1                    
INFO:main: top_c               : 1                    
INFO:main: super_noise_std     : 0.3                  
INFO:main: batch_size          : 100                  
INFO:main: dataset             : mnist                
INFO:main: valid_set_size      : 10000                
INFO:main: num_epochs          : 150                  
INFO:main: whiten_zca          : 0                    
INFO:main: unlabeled_samples   : 60000                
INFO:main: decoder_spec        : ('0', '0', '0', '0', '0', '0', 'gauss') 
INFO:main: valid_batch_size    : 100                  
INFO:main: denoising_cost_x    : (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.0) 
INFO:main: f_local_noise_std   : 0.3                  
INFO:main: cmd                 : train                
INFO:main: act                 : relu                 
INFO:main: lrate_decay         : 0.67                 
INFO:main: seed                : 1                    
INFO:main: lr                  : 0.002                
INFO:main: save_to             : mnist_all_gamma      
INFO:main: save_dir            : results/mnist_all_gamma0 
INFO:main: commit              :                      
INFO:main: contrast_norm       : 0                    
INFO:main: encoder_layers      : ('1000', '500', '250', '250', '250', '10') 
INFO:main: labeled_samples     : 60000                
Traceback (most recent call last):
  File "./run.py", line 651, in <module>
    if train(d) is None:
  File "./run.py", line 405, in train
    in_dim, data, whiten, cnorm = setup_data(p, test_set=False)
  File "./run.py", line 240, in setup_data
    train_set = dataset_class("train")
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 36, in __init__
    super(MNIST, self).__init__(self.data_path, which_set, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 40, in data_path
    return os.path.join(config.data_path, self.filename)
  File "/usr/local/lib/python2.7/dist-packages/fuel/config_parser.py", line 101, in __getattr__
    "provided: {}.".format(key))
**_fuel.config_parser.ConfigurationError: Configuration not set and no default provided: data_path._**
wangxiao@GTX980:~/Desktop/ladder-master$

**Comment by wangxiao5791509** [comment] 2016-07-02 08:28
![screenshot from 2016-07-02 16 27 46](https://cloud.githubusercontent.com/assets/12805786/16539322/fed145aa-4071-11e6-8b16-b9780e913368.png)

**Comment by Baitman** [comment] 2016-07-05 19:15
Running into the same problem. The only exception is that I tried it using the mnist_all_full. 
![2016-07-05-150947_1224x643_scrot](https://cloud.githubusercontent.com/assets/11700790/16596717/3e40436e-42c3-11e6-9a96-758ea9f20ce6.png)

**Comment by Baitman** [comment] 2016-07-05 20:37
**Update:** Tried downgrading Theano to version 0.7 [the version that probably would have been used around the time the code was published]. The Tensor warning has been suppressed, but the error reported in this issue still persists.

**Comment by wangxiao5791509** [comment] 2016-07-06 07:32
But the auther of the paper did not even release a email address to us, I could not contract with him ! It is really confused me ... 

Hope the auther could give us a replay ...

**Comment by petteriTeikari** [comment] 2016-07-07 03:28
I am not the author @wangxiao5791509 but that is not related to the ladder network implementation, but to the Fuel package used by the authors.

You need to define that to a file which is not the most elegant way imho:
http://fuel.readthedocs.io/en/latest/built_in_datasets.html#environment-variable
```
# ~/.fuelrc
data_path: "/first/path/to/my/data:/second/path/to/my/data"
```

**Comment by Wakeupbuddy** [comment] 2016-07-07 04:21
or you can add these 2 lines in run.py:
```
from fuel import config
config.data_path = '/path/to/your/data'
```

**Comment by Baitman** [comment] 2016-07-07 14:23
@Wakeupbuddy Adding those lines ended up working after all. Thanks. @petteriTeikari I found that documentation yesterday, but the method you described didn't work for me. Thanks though.

**Comment by wangxiao5791509** [comment] 2016-07-10 12:44
I am new to python and I don't know how to solve it. Well, thanks for your answer and I will try it later. @petteriTeikari

**Comment by wangxiao5791509** [comment] 2016-07-10 12:57
@petteriTeikari  I have one question: Do you know how to use this ladder network to run other classification datasets ? such as caltech-256 or cifar-100 ?  Just use that package **Fuel** ??

**Comment by hotloo** [comment] 2016-07-22 08:33
Hi! 

Ladder master is just updated with blocks and fuel 0.2 support. The fuel configuration should be set prior to running the code according to the configuration page: 

http://fuel.readthedocs.io/en/latest/built_in_datasets.html

In fuel 0.2, there are more datasets supported, and it should be straightforward to test it with the ladder codebase. 

@wangxiao5791509 Could you please try update your master, configure fuel and then try out some of the examples that are in the README? Please let me know if you have any issues! Also, if the issue is resolved, could you also please close this issue? 

Sorry for not responding, and we will try to respond to the issue faster going forward!

**Closed** 2016-09-06 20:42 UTC
