### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by kleiba** [CuriousAI/ladder#11] opened 2016-05-19 09:58 UTC
I'm trying to run one of the commands from the README file:

```
THEANO_FLAGS='floatX=float32' ./run.py train --encoder-layers 1000-500-250-250-250-10 --decoder-spec gauss --denoising-cost-x 1000,1,0.01,0.01,0.01,0.01,0.01 --labeled-samples 60000 --unlabeled-samples 60000 --seed 1 -- mnist_all_full
```

but keep getting the following error:

```
Traceback (most recent call last):
  File "./run.py", line 651, in <module>
    if train(d) is None:
  File "./run.py", line 423, in train
    step_rule=Adam(learning_rate=ladder.lr))
  File "/usr/local/lib/python2.7/site-packages/blocks/algorithms/__init__.py", line 794, in __init__
    self.learning_rate = shared_floatx(learning_rate, "learning_rate")
  File "/usr/local/lib/python2.7/site-packages/blocks/utils/__init__.py", line 167, in shared_floatx
    return theano.shared(theano._asarray(value, dtype=dtype),
  File "/usr/local/lib/python2.7/site-packages/theano/misc/safe_asarray.py", line 33, in _asarray
    rval = numpy.asarray(a, dtype=dtype, order=order)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 474, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

If I look at the parameters passed to "array(...)" in line 474 of numeric.py, I see the following:

```
a ->  learning_rate 
type(a) -> <class 'theano.tensor.sharedvar.ScalarSharedVariable'> 
dtype -> float64
```

Could this be due to a version conflict of any of the involved libraries?

**Comment by kleiba** [comment] 2016-06-06 07:31
Hello,

Just to follow up on my bug report above: is anyone looking into this issue? It would be greatly appreciated.

Thanks a lot.

**Comment by hotloo** [comment] 2016-07-20 10:43
Hi! 

Sorry for the slow response. It seems to be a blocks version mismatch issue. We are updating this repo to use blocks 0.2 and fuel 0.2. I hope that fixed this issue. Stay tuned! 

Cheers,
and thanks again for trying out our code here!

**Comment by kleiba** [comment] 2016-07-20 13:45
Thanks for taking the time, hotloo!
I'll be awaiting the update soon and report back.

**Comment by hotloo** [comment] 2016-07-20 20:47
Can you take a look if this problem is still there with the newly pushed branch blocks-fuel-0.2-support? Also, if possible, could you please match your development environment to the environment.yml that is also pushed there?

**Comment by kleiba** [comment] 2016-07-22 08:14
Hi hotloo,
I will be happy to try this out. Unfortunately, though, I will be on vacation for three weeks and thus won't be able to test the new update before the end of August.
Thanks a lot.

**Comment by hotloo** [comment] 2016-07-22 08:46
I think this *should* be fixed. I have encountered this issue myself locally. 

The problem is really the change of syntax on blocks & fuel internals. I have updated them, and then now it should be causing no issue. I will close this since I have reproduced and fixed them. If your problem persists when you try it out, please let me know, and we can take a look at it together. 

Thanks for your reply!

**Closed by hotloo** 2016-07-22 08:46 UTC
